### PR TITLE
Add a legend

### PR DESCRIPTION
**Pull request by Zhouzi**
The colors' meaning is not really obvious so this PR adds a legend that looks like this:

large

small

I first used the same gray as the label's but the text looked lighter due to the colored rounds.

### CODE REVIEW

**Comment by surma** [comment]
Awesome! Thanks for your work, @Zhouzi! This LGTM, gonna wait for @paullewis to ACK this as well :)

**Comment by oldergod** [comment]
I know the new reaction feature on github was created for message like this to be avoided but, this simple PR would really help the usability of this awesome website.

**Comment by surma** [comment]
@Zhouzi Sorry for the delay on this. I just did cross-browser check and everything and I am about to merge this PR :tada: However, before I can do that, I need to ask you to sign Google’s CLA that we are allowed to use your contribution here :)

Please go [here](https://cla.developers.google.com/) and let me know once you have signed the CLA.

**Comment by Zhouzi** [comment]
It's already signed it and the checks seems to be ok so I guess we're all good :)

**Comment by surma** [comment]
Hm.... I could have sworn I couldn’t find your signature earlier. All good now. Thanks again @Zhouzi :)

**Comment by surma** [comment]
It’s (a)liiiiiive 👾

**Comment by Zhouzi** [comment]
Hell yeah, it is! 👽

**Pull request merged**
