### PR TITLE
sw-precache for SW generation

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @paullewis @surma 

Benefits of using `sw-precache` vs. the existing `sw.js`:

- Each cached asset is managed independently. Changes to one asset can be picked up without having to bump `@VERSION@`, triggering the expiration of the entire cache.
- The list of resources to precache is generated at build-time based on the actual contents of `dist/`. It doesn't need to be maintained via a JavaScript array in `sw.js`.
- A cache-busting URL parameter is used to ensure that when there is an update to a previously cached asset, a fresh copy of the asset is fetched from the server, bypassing the browser cache.

I have a feeling that the 404 behavior may change as a result of moving to this `sw-precache` setup, but it's hard for me to test the exact behavior, since I can't get the dev server to actually trigger a 404. How does the serving environment differ in production?

### CODE REVIEW

**Comment by surma** [comment]
Hey @jeffposnick,

thanks for whipping up the PR! We actually actively considered sw-toolbox while writing (how could we not?), but decided against it.

The theme of this project involves a pretty opinionated minimalism. No frameworks or libraries were used in the UI and we wanted to keep that going for the service worker as well. The project is small enough that people can actually read through it in a short amount of time. So instead of going with best practices and common tooling, we decided to stay as vanilla as possible so people can read the code and see what all these libraries that you usually use do under the hood.

Our current 404 solution is pretty hacky and will be revised shortly.

**Comment by surma** [comment]
I also totally meant “sw-precache”. (Full disclosure: We also considered sw-toolbox and came to the same conclusion for the same reasons).

**Comment by jeffposnick** [comment]
I'd argue that at least two of the three benefits that you'd get from using `sw-precache` are important enough that they should be addressed via a "vanilla" JS solution, in that case.

Versioning each independent resource and only expiring the ones that change goes a long way towards being respectful of users' bandwidth. This has been par for the course for Android apps [since 2012](http://www.engadget.com/2012/06/27/google-brings-incremental-app-updates-to-android-added-encrypti/), and the same applies to iOS apps.

If you don't cache-bust your requests in your `install` handler, you run the risk of serving stale resources from your service worker for an indefinite amount of time. This is more of an edge case that would only affect repeat users who visit your site before and after a service worker update, but with `Cache-Control:max-age=3600` the window for the right sequence of events being triggered is wide enough.

(The third issue, having to maintain an independent list of assets to precache within a JavaScript array, isn't too much of an issue in practice. It's more developer ergonomics.)

So feel free to close this PR if it goes against the philosophy of the project, but I do think the issues I bring up should be addressed in whatever service worker code is used.

**Comment by surma** [comment]
> Versioning each independent resource and only expiring the ones that change goes a long way towards being respectful of users' bandwidth

I was under the impression that good old ETags would take care of not downloading resources that didn’t change. But I have to admit that I didn’t check that.

I am going to close this, as I don’t think we are changing course, but I will definitely recheck your  (valid) concerns regarding our vanilla implementation. Thanks Jeff :)

**Pull request closed without merging**
